// Autogenerated code: assumes that 'modelObject' is 
// a RList object


/**
 * Gets the <code>assign</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the assign field
 */
public int[] getAssign() {
    return modelObject.at("assign").asIntArray();
}

/**
 * Gets the <code>coefficients</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the coefficients field
 */
public double[] getCoefficients() {
    return modelObject.at("coefficients").asDoubleArray();
}

/**
 * Gets the <code>df.residual</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the df.residual field
 */
public int getDfResidual() {
    return modelObject.at("df.residual").asInt();
}

/**
 * Gets the <code>effects</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the effects field
 */
public double[] getEffects() {
    return modelObject.at("effects").asDoubleArray();
}

/**
 * Gets the <code>fitted.values</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the fitted.values field
 */
public double[] getFittedValues() {
    return modelObject.at("fitted.values").asDoubleArray();
}

/**
 * Gets the <code>model</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the model field
 */
public RList getModel() {
    return modelObject.at("model").asList();
}

/**
 * Gets the <code>qr</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the qr field
 */
public RList getQr() {
    return modelObject.at("qr").asList();
}

/**
 * Gets the <code>rank</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the rank field
 */
public int getRank() {
    return modelObject.at("rank").asInt();
}

/**
 * Gets the <code>residuals</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the residuals field
 */
public double[] getResiduals() {
    return modelObject.at("residuals").asDoubleArray();
}

/**
 * Gets the <code>xlevels</code> field of an <code>'lm'</code> object.
 *
 * @return The value of the xlevels field
 */
public RList getXlevels() {
    return modelObject.at("xlevels").asList();
}

