/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "urbanek@research.att.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "JRI"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "JRI 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "jri"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1
