# JRI - Java/R Interface      experimental!
#--------------------------------------------------------------------------
# See Makefile.all for the actual building process

# The values are all auto-configured
RHOME=/usr/local/lib/R
JAVAC=/usr/local/share/java/jdk1.5.0/bin/javac $(JFLAGS)
JAVAH=/usr/local/share/java/jdk1.5.0/bin/javah
JAVA=/usr/local/share/java/jdk1.5.0/bin/java

JRILIB=libjri.so

include Makefile.all
